-- AlterEnum
ALTER TYPE "AuditEntityType" ADD VALUE 'QCTO_REQUEST';
ALTER TYPE "AuditEntityType" ADD VALUE 'SUBMISSION_RESOURCE';
ALTER TYPE "AuditEntityType" ADD VALUE 'SUBMISSION';
ALTER TYPE "AuditEntityType" ADD VALUE 'QUALIFICATION';
