// Test fixtures - reusable test data
import type { User, Institution, Learner, Submission, Readiness } from "@prisma/client";

export const mockInstitution: Omit<Institution, "created_at" | "updated_at"> = {
  institution_id: "inst-123",
  legal_name: "Test Institution",
  trading_name: "Test Inst",
  institution_type: "PRIVATE_SDP",
  registration_number: "REG123",
  tax_compliance_pin: "TAX123",
  physical_address: "123 Test St",
  postal_address: "PO Box 123",
  province: "Gauteng",
  delivery_modes: ["FACE_TO_FACE"],
  status: "APPROVED",
  contact_person_name: "John Doe",
  contact_email: "contact@testinst.co.za",
  contact_number: "0123456789",
  deleted_at: null,
};

export const mockUser: Omit<User, "created_at" | "updated_at"> = {
  user_id: "user-123",
  institution_id: "inst-123",
  qcto_id: null,
  role: "INSTITUTION_ADMIN",
  first_name: "John",
  last_name: "Doe",
  email: "john.doe@testinst.co.za",
  emailVerified: null,
  phone: "0123456789",
  password_hash: "$2a$10$hashedpassword",
  status: "ACTIVE",
  image: null,
  deleted_at: null,
};

export const mockLearner: Omit<Learner, "created_at" | "updated_at"> = {
  learner_id: "learner-123",
  institution_id: "inst-123",
  user_id: null,
  national_id: "9001015009088",
  alternate_id: null,
  first_name: "Jane",
  last_name: "Smith",
  birth_date: new Date("1990-01-01"),
  gender_code: "F",
  nationality_code: "ZA",
  home_language_code: "en",
  disability_status: null,
  popia_consent: true,
  consent_date: new Date("2024-01-01"),
  deleted_at: null,
};

export const mockSubmission: Omit<Submission, "created_at" | "updated_at"> = {
  submission_id: "sub-123",
  institution_id: "inst-123",
  title: "Test Compliance Pack",
  submission_type: "COMPLIANCE_PACK",
  status: "SUBMITTED",
  submitted_at: new Date(),
  submitted_by: "user-123",
  reviewed_at: null,
  reviewed_by: null,
  review_notes: null,
  deleted_at: null,
};

export const mockReadiness: Omit<Readiness, "created_at" | "updated_at"> = {
  readiness_id: "ready-123",
  institution_id: "inst-123",
  qualification_title: "Test Qualification",
  saqa_id: "12345",
  nqf_level: 5,
  curriculum_code: "CUR123",
  delivery_mode: "FACE_TO_FACE",
  readiness_status: "SUBMITTED",
  submission_date: new Date(),
  deleted_at: null,
  // Optional fields
  self_assessment_completed: true,
  self_assessment_remarks: null,
  registration_type: null,
  professional_body_registration: null,
  training_site_address: null,
  ownership_type: null,
  number_of_training_rooms: null,
  room_capacity: null,
  facilitator_learner_ratio: null,
  learning_material_exists: null,
  knowledge_module_coverage: null,
  practical_module_coverage: null,
  curriculum_alignment_confirmed: null,
  fire_extinguisher_available: null,
  fire_extinguisher_service_date: null,
  emergency_exits_marked: null,
  accessibility_for_disabilities: null,
  first_aid_kit_available: null,
  ohs_representative_name: null,
  lms_name: null,
  max_learner_capacity: null,
  internet_connectivity_method: null,
  isp: null,
  backup_frequency: null,
  data_storage_description: null,
  security_measures_description: null,
  wbl_workplace_partner_name: null,
  wbl_agreement_type: null,
  wbl_agreement_duration: null,
  wbl_components_covered: null,
  wbl_learner_support_description: null,
  wbl_assessment_responsibility: null,
  policies_procedures_notes: null,
  facilitators_notes: null,
};
