-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'INVITE_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'READINESS_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'REVIEW_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE 'BULK_INVITE_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'INSTITUTION_CREATED';
